export const endpoints_properties = 
  {
    "ENDPOINT_IDENTITY_LOCAL" : "http://localhost:4728",
    "ENDPOINT_PERSONAL_DETAILS_LOCAL" : "http://localhost:4753",
    "ENDPOINT_SKILLS_LOCAL" : "http://localhost:4744",
    "ENDPOINT_JOB_TITLES_LOCAL" : "http://localhost:4727",
    "ENDPOINT_INDUSTRIES_LOCAL" :"http://localhost:4719",
    "ENDPOINT_COMPANIES_LOCAL" : "http://localhost:4707",
    "ENDPOINT_CITIES_LOCAL":"http://localhost:4706",
    "ENDPOINT_CURRENCIES_LOCAL" : "http://localhost:4767",
    "ENDPOINT_TIMEZONES_LOCAL" : "http://localhost:4703",
    "ENDPOINT_DEGREES_LOCAL" : "http://localhost:4702",
    "ENDPOINT_INSTITUTES_LOCAL": "http://localhost:4721",
    "ENDPOINT_LANGUAGES_LOCAL" :"http://localhost:4729",
    "ENDPOINT_SEARCH_SERVICE_PROVIDER_LOCAL" : "http://localhost:4738",
    "ENDPOINT_SEARCH_TRAINING_LOCAL" : "http://localhost:4768",
    "ENDPOINT_USER_TRAINING_LOCAL": "http://localhost:4750",
    "ENDPOINT_TRAINING_WISH_LOCAL": "http://localhost:4724",
    "ENDPOINT_COUNTRIES_LOCAL":"http://localhost:4711",
    "ENDPOINT_STATES_LOCAL" : "http://localhost:4745",
    "ENDPOINT_TRAINING_LOCAL" : "http://localhost:4754",
    "ENDPOINT_TRAINING_CENTRE_LOCAL" : "http://localhost:4731",
    "ENDPOINT_INTERVIEW_SCHEDULAR_LOCAL" : "http://localhost:4722",
    "ENDPOINT_RECOMMENDED_TRAINING_LOCAL" : "http://localhost:4756",
    "ENDPOINT_DEV" : "https://rk5r6o4uo8.execute-api.ap-south-1.amazonaws.com/dev",
  }